package com.przemo.busessearchinterfaces.data;
// Generated 2015-08-09 11:52:28 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Buses generated by hbm2java
 */
public class Buses  implements java.io.Serializable {


     private int id;
     private String make;
     private Date manufacturedon;
     private Date usedSince;
     private Date endDate;
     private Set lineses = new HashSet(0);

    public Buses() {
    }

	
    public Buses(int id, Date manufacturedon, Date usedSince) {
        this.id = id;
        this.manufacturedon = manufacturedon;
        this.usedSince = usedSince;
    }
    public Buses(int id, String make, Date manufacturedon, Date usedSince, Date endDate, Set lineses) {
       this.id = id;
       this.make = make;
       this.manufacturedon = manufacturedon;
       this.usedSince = usedSince;
       this.endDate = endDate;
       this.lineses = lineses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getMake() {
        return this.make;
    }
    
    public void setMake(String make) {
        this.make = make;
    }
    public Date getManufacturedon() {
        return this.manufacturedon;
    }
    
    public void setManufacturedon(Date manufacturedon) {
        this.manufacturedon = manufacturedon;
    }
    public Date getUsedSince() {
        return this.usedSince;
    }
    
    public void setUsedSince(Date usedSince) {
        this.usedSince = usedSince;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public Set getLineses() {
        return this.lineses;
    }
    
    public void setLineses(Set lineses) {
        this.lineses = lineses;
    }




}


