package com.przemo.busessearchinterfaces.data;
// Generated 2015-04-26 15:55:11 by Hibernate Tools 4.3.1



/**
 * Distances generated by hbm2java
 */
public class Distances  implements java.io.Serializable {


     private int id;
     private Stations stationsByStationTo;
     private Stations stationsByStationFrom;
     private Double distance;

    public Distances() {
    }

	
    public Distances(int id) {
        this.id = id;
    }
    public Distances(int id, Stations stationsByStationTo, Stations stationsByStationFrom, Double distance) {
       this.id = id;
       this.stationsByStationTo = stationsByStationTo;
       this.stationsByStationFrom = stationsByStationFrom;
       this.distance = distance;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Stations getStationsByStationTo() {
        return this.stationsByStationTo;
    }
    
    public void setStationsByStationTo(Stations stationsByStationTo) {
        this.stationsByStationTo = stationsByStationTo;
    }
    public Stations getStationsByStationFrom() {
        return this.stationsByStationFrom;
    }
    
    public void setStationsByStationFrom(Stations stationsByStationFrom) {
        this.stationsByStationFrom = stationsByStationFrom;
    }
    public Double getDistance() {
        return this.distance;
    }
    
    public void setDistance(Double distance) {
        this.distance = distance;
    }




}


