package com.przemo.busessearchinterfaces.data;
// Generated 2015-05-06 21:54:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Lines generated by hbm2java
 */
public class Lines  implements java.io.Serializable {


     private int id;
     private Buses buses;
     private String decription;
     private Set timetableses = new HashSet(0);
     private Set distanceses = new HashSet(0);

    public Lines() {
    }

	
    public Lines(int id, Buses buses) {
        this.id = id;
        this.buses = buses;
    }
    public Lines(int id, Buses buses, String decription, Set timetableses, Set distanceses) {
       this.id = id;
       this.buses = buses;
       this.decription = decription;
       this.timetableses = timetableses;
       this.distanceses = distanceses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Buses getBuses() {
        return this.buses;
    }
    
    public void setBuses(Buses buses) {
        this.buses = buses;
    }
    public String getDecription() {
        return this.decription;
    }
    
    public void setDecription(String decription) {
        this.decription = decription;
    }
    public Set getTimetableses() {
        return this.timetableses;
    }
    
    public void setTimetableses(Set timetableses) {
        this.timetableses = timetableses;
    }
    public Set getDistanceses() {
        return this.distanceses;
    }
    
    public void setDistanceses(Set distanceses) {
        this.distanceses = distanceses;
    }




}


