package com.przemo.busessearchinterfaces.data;
// Generated 2015-05-02 20:40:15 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Lines generated by hbm2java
 */
public class Lines  implements java.io.Serializable {


     private int id;
     private Buses buses;
     private String decription;
     private Set routeses = new HashSet(0);

    public Lines() {
    }

	
    public Lines(int id, Buses buses) {
        this.id = id;
        this.buses = buses;
    }
    public Lines(int id, Buses buses, String decription, Set routeses) {
       this.id = id;
       this.buses = buses;
       this.decription = decription;
       this.routeses = routeses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Buses getBuses() {
        return this.buses;
    }
    
    public void setBuses(Buses buses) {
        this.buses = buses;
    }
    public String getDecription() {
        return this.decription;
    }
    
    public void setDecription(String decription) {
        this.decription = decription;
    }
    public Set getRouteses() {
        return this.routeses;
    }
    
    public void setRouteses(Set routeses) {
        this.routeses = routeses;
    }




}


