package com.przemo.busessearchinterfaces.data;
// Generated 2015-04-26 15:55:11 by Hibernate Tools 4.3.1



/**
 * Lines generated by hbm2java
 */
public class Lines  implements java.io.Serializable {


     private int id;
     private Buses buses;
     private String decription;

    public Lines() {
    }

	
    public Lines(int id, Buses buses) {
        this.id = id;
        this.buses = buses;
    }
    public Lines(int id, Buses buses, String decription) {
       this.id = id;
       this.buses = buses;
       this.decription = decription;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Buses getBuses() {
        return this.buses;
    }
    
    public void setBuses(Buses buses) {
        this.buses = buses;
    }
    public String getDecription() {
        return this.decription;
    }
    
    public void setDecription(String decription) {
        this.decription = decription;
    }




}


