package com.przemo.busessearchinterfaces.data;
// Generated 2015-04-26 15:55:11 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Routes generated by hbm2java
 */
public class Routes  implements java.io.Serializable {


     private int id;
     private Stations stations;
     private Date arrivalTime;
     private Date departureTime;

    public Routes() {
    }

	
    public Routes(int id, Stations stations) {
        this.id = id;
        this.stations = stations;
    }
    public Routes(int id, Stations stations, Date arrivalTime, Date departureTime) {
       this.id = id;
       this.stations = stations;
       this.arrivalTime = arrivalTime;
       this.departureTime = departureTime;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Stations getStations() {
        return this.stations;
    }
    
    public void setStations(Stations stations) {
        this.stations = stations;
    }
    public Date getArrivalTime() {
        return this.arrivalTime;
    }
    
    public void setArrivalTime(Date arrivalTime) {
        this.arrivalTime = arrivalTime;
    }
    public Date getDepartureTime() {
        return this.departureTime;
    }
    
    public void setDepartureTime(Date departureTime) {
        this.departureTime = departureTime;
    }




}


