package com.przemo.busessearchinterfaces.data;
// Generated 2015-05-02 20:40:15 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Routes generated by hbm2java
 */
public class Routes  implements java.io.Serializable {


     private int id;
     private Lines lines;
     private Stations stationsByIdStation;
     private Stations stationsByIdStationFrom;
     private Date arrivalTime;
     private Date departureTime;

    public Routes() {
    }

	
    public Routes(int id, Stations stationsByIdStation) {
        this.id = id;
        this.stationsByIdStation = stationsByIdStation;
    }
    public Routes(int id, Lines lines, Stations stationsByIdStation, Stations stationsByIdStationFrom, Date arrivalTime, Date departureTime) {
       this.id = id;
       this.lines = lines;
       this.stationsByIdStation = stationsByIdStation;
       this.stationsByIdStationFrom = stationsByIdStationFrom;
       this.arrivalTime = arrivalTime;
       this.departureTime = departureTime;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Lines getLines() {
        return this.lines;
    }
    
    public void setLines(Lines lines) {
        this.lines = lines;
    }
    public Stations getStationsByIdStation() {
        return this.stationsByIdStation;
    }
    
    public void setStationsByIdStation(Stations stationsByIdStation) {
        this.stationsByIdStation = stationsByIdStation;
    }
    public Stations getStationsByIdStationFrom() {
        return this.stationsByIdStationFrom;
    }
    
    public void setStationsByIdStationFrom(Stations stationsByIdStationFrom) {
        this.stationsByIdStationFrom = stationsByIdStationFrom;
    }
    public Date getArrivalTime() {
        return this.arrivalTime;
    }
    
    public void setArrivalTime(Date arrivalTime) {
        this.arrivalTime = arrivalTime;
    }
    public Date getDepartureTime() {
        return this.departureTime;
    }
    
    public void setDepartureTime(Date departureTime) {
        this.departureTime = departureTime;
    }




}


