package com.przemo.busessearchinterfaces.data;
// Generated 2015-05-06 21:54:18 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Stations generated by hbm2java
 */
public class Stations  implements java.io.Serializable {


     private int id;
     private String name;
     private Serializable coordinates;
     private Set distancesesForStationTo = new HashSet(0);
     private Set distancesesForStationFrom = new HashSet(0);
     private Set timetableses = new HashSet(0);

    public Stations() {
    }

	
    public Stations(int id, String name) {
        this.id = id;
        this.name = name;
    }
    public Stations(int id, String name, Serializable coordinates, Set distancesesForStationTo, Set distancesesForStationFrom, Set timetableses) {
       this.id = id;
       this.name = name;
       this.coordinates = coordinates;
       this.distancesesForStationTo = distancesesForStationTo;
       this.distancesesForStationFrom = distancesesForStationFrom;
       this.timetableses = timetableses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Serializable getCoordinates() {
        return this.coordinates;
    }
    
    public void setCoordinates(Serializable coordinates) {
        this.coordinates = coordinates;
    }
    public Set getDistancesesForStationTo() {
        return this.distancesesForStationTo;
    }
    
    public void setDistancesesForStationTo(Set distancesesForStationTo) {
        this.distancesesForStationTo = distancesesForStationTo;
    }
    public Set getDistancesesForStationFrom() {
        return this.distancesesForStationFrom;
    }
    
    public void setDistancesesForStationFrom(Set distancesesForStationFrom) {
        this.distancesesForStationFrom = distancesesForStationFrom;
    }
    public Set getTimetableses() {
        return this.timetableses;
    }
    
    public void setTimetableses(Set timetableses) {
        this.timetableses = timetableses;
    }




}


