package com.przemo.busessearchinterfaces.data;
// Generated 2015-04-26 15:55:11 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Stations generated by hbm2java
 */
public class Stations  implements java.io.Serializable {


     private int id;
     private String name;
     private Set routeses = new HashSet(0);
     private Set distancesesForStationTo = new HashSet(0);
     private Set distancesesForStationFrom = new HashSet(0);

    public Stations() {
    }

	
    public Stations(int id, String name) {
        this.id = id;
        this.name = name;
    }
    public Stations(int id, String name, Set routeses, Set distancesesForStationTo, Set distancesesForStationFrom) {
       this.id = id;
       this.name = name;
       this.routeses = routeses;
       this.distancesesForStationTo = distancesesForStationTo;
       this.distancesesForStationFrom = distancesesForStationFrom;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getRouteses() {
        return this.routeses;
    }
    
    public void setRouteses(Set routeses) {
        this.routeses = routeses;
    }
    public Set getDistancesesForStationTo() {
        return this.distancesesForStationTo;
    }
    
    public void setDistancesesForStationTo(Set distancesesForStationTo) {
        this.distancesesForStationTo = distancesesForStationTo;
    }
    public Set getDistancesesForStationFrom() {
        return this.distancesesForStationFrom;
    }
    
    public void setDistancesesForStationFrom(Set distancesesForStationFrom) {
        this.distancesesForStationFrom = distancesesForStationFrom;
    }




}


