package com.przemo.busessearchinterfaces.data;
// Generated 2015-08-09 11:52:28 by Hibernate Tools 4.3.1



/**
 * TimetablesTypes generated by hbm2java
 */
public class TimetablesTypes  implements java.io.Serializable {


     private int id;
     private String name;

    public TimetablesTypes() {
    }

    public TimetablesTypes(int id, String name) {
       this.id = id;
       this.name = name;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


