package com.przemo.busessearchinterfaces.data;
// Generated 2015-08-09 11:52:28 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Timetables generated by hbm2java
 */
public class Timetables  implements java.io.Serializable {


     private int id;
     private Lines lines;
     private Stations stationsByNodeTo;
     private Stations stationsByNodeFrom;
     private Date arriveAtNodeFrom;
     private Date departToNodeTo;

    public Timetables() {
    }

	
    public Timetables(int id, Lines lines, Stations stationsByNodeFrom) {
        this.id = id;
        this.lines = lines;
        this.stationsByNodeFrom = stationsByNodeFrom;
    }
    public Timetables(int id, Lines lines, Stations stationsByNodeTo, Stations stationsByNodeFrom, Date arriveAtNodeFrom, Date departToNodeTo) {
       this.id = id;
       this.lines = lines;
       this.stationsByNodeTo = stationsByNodeTo;
       this.stationsByNodeFrom = stationsByNodeFrom;
       this.arriveAtNodeFrom = arriveAtNodeFrom;
       this.departToNodeTo = departToNodeTo;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Lines getLines() {
        return this.lines;
    }
    
    public void setLines(Lines lines) {
        this.lines = lines;
    }
    public Stations getStationsByNodeTo() {
        return this.stationsByNodeTo;
    }
    
    public void setStationsByNodeTo(Stations stationsByNodeTo) {
        this.stationsByNodeTo = stationsByNodeTo;
    }
    public Stations getStationsByNodeFrom() {
        return this.stationsByNodeFrom;
    }
    
    public void setStationsByNodeFrom(Stations stationsByNodeFrom) {
        this.stationsByNodeFrom = stationsByNodeFrom;
    }
    public Date getArriveAtNodeFrom() {
        return this.arriveAtNodeFrom;
    }
    
    public void setArriveAtNodeFrom(Date arriveAtNodeFrom) {
        this.arriveAtNodeFrom = arriveAtNodeFrom;
    }
    public Date getDepartToNodeTo() {
        return this.departToNodeTo;
    }
    
    public void setDepartToNodeTo(Date departToNodeTo) {
        this.departToNodeTo = departToNodeTo;
    }




}


