package com.przemo.busessearchinterfaces.data;
// Generated 2015-05-06 21:54:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TimetablesTypes generated by hbm2java
 */
public class TimetablesTypes  implements java.io.Serializable {


     private int id;
     private String name;
     private Set timetableses = new HashSet(0);

    public TimetablesTypes() {
    }

	
    public TimetablesTypes(int id, String name) {
        this.id = id;
        this.name = name;
    }
    public TimetablesTypes(int id, String name, Set timetableses) {
       this.id = id;
       this.name = name;
       this.timetableses = timetableses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getTimetableses() {
        return this.timetableses;
    }
    
    public void setTimetableses(Set timetableses) {
        this.timetableses = timetableses;
    }




}


