package com.przemo.busessearchinterfaces.data;
// Generated 2015-05-06 21:54:18 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Timetables generated by hbm2java
 */
public class Timetables  implements java.io.Serializable {


     private int id;
     private Lines lines;
     private Stations stations;
     private TimetablesTypes timetablesTypes;
     private Date stationTime;

    public Timetables() {
    }

	
    public Timetables(int id, Date stationTime) {
        this.id = id;
        this.stationTime = stationTime;
    }
    public Timetables(int id, Lines lines, Stations stations, TimetablesTypes timetablesTypes, Date stationTime) {
       this.id = id;
       this.lines = lines;
       this.stations = stations;
       this.timetablesTypes = timetablesTypes;
       this.stationTime = stationTime;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Lines getLines() {
        return this.lines;
    }
    
    public void setLines(Lines lines) {
        this.lines = lines;
    }
    public Stations getStations() {
        return this.stations;
    }
    
    public void setStations(Stations stations) {
        this.stations = stations;
    }
    public TimetablesTypes getTimetablesTypes() {
        return this.timetablesTypes;
    }
    
    public void setTimetablesTypes(TimetablesTypes timetablesTypes) {
        this.timetablesTypes = timetablesTypes;
    }
    public Date getStationTime() {
        return this.stationTime;
    }
    
    public void setStationTime(Date stationTime) {
        this.stationTime = stationTime;
    }




}


